# Generated by Django 4.1.7 on 2023-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Рынок обмена')),
                ('api_url', models.URLField(max_length=150, verbose_name='API')),
            ],
        ),
    ]
