# Generated by Django 4.1.7 on 2023-03-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangemarket',
            options={'ordering': ['pk'], 'verbose_name': 'Рынок обмена', 'verbose_name_plural': 'Рынки обмена'},
        ),
        migrations.RenameField(
            model_name='exchangemarket',
            old_name='name',
            new_name='marketname',
        ),
    ]
