# Generated by Django 4.1.7 on 2023-03-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_exchangemarket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemarket',
            name='api_url',
            field=models.CharField(max_length=150, verbose_name='API'),
        ),
    ]
